; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:teensy40]
lib_deps = 
	adafruit/Adafruit BME280 Library@^2.3.0 ; Environmental Sensor Unit
	adafruit/Adafruit Unified Sensor@^1.1.15 ; Global Sensor Drivers
    adafruit/Adafruit BNO055@^1.6.4 ; Inertial Measuring Unit
    adafruit/Adafruit INA260 Library@^1.5.3 ; Power Sensor Unit
platform = teensy
board = teensy40
framework = arduino
build_src_filter = 
    +<*>
    -<components/BME280_Sensor.cpp>
    -<components/BNO055.cpp>
    -<components/NEO_M9N.cpp>

[env:BME280_TEST]
lib_deps =
	adafruit/Adafruit BME280 Library@^2.3.0 ; Environmental Sensor Unit
platform = teensy
board = teensy40
framework = arduino
build_src_filter = 
    +<*>
    +<components/BME280_Sensor.cpp>
    -<components/BNO055.cpp>
    -<components/NEO_M9N.cpp>
    -<main.cpp>

[env:BNO055_TEST]
lib_deps = 
    adafruit/Adafruit BNO055@^1.6.4 ; Inertial Measuring Unit
platform = teensy
board = teensy40
framework = arduino
build_src_filter = 
    +<*>
    +<components/SHC_BNO055.cpp>
    +<components/BME280_Sensor.cpp>
    +<components/SHC_M9N.cpp>
    +<main.cpp>
	-<components/INA260.cpp>
    